"""Synthetic environments: assets, topology and seeded findings. Everything here is fake and labeled as such."""

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
CATEGORIES = {
    "web": "Web",
    "transport": "Transport",
    "auth": "Auth/Access",
    "config": "Configuration",
    "exposure": "Exposure",
}


def _f(fid, asset, title, severity, category, tags, evidence, why, confidence, action, rem_priority, rem_explain, snippet_lang=None, snippet=None):
    return {
        "id": fid,
        "asset_id": asset,
        "title": title,
        "severity": severity,
        "category": category,
        "tags": tags,
        "evidence": evidence,
        "why_it_matters": why,
        "confidence": confidence,
        "recommended_action": action,
        "remediation": {
            "priority": rem_priority,
            "explanation": rem_explain,
            "snippet_language": snippet_lang,
            "snippet": snippet,
        },
    }


ENVIRONMENTS = [
    {
        "id": "acme-retail",
        "name": "Acme Retail",
        "tagline": "Storefront & Checkout Platform",
        "sector": "E-commerce",
        "infra": "AWS EKS · Cloudflare · Postgres · S3",
        "description": "Consumer storefront processing synthetic payment tokens and customer PII across a public checkout API and an internal admin portal.",
        "endpoint_count": 14,
        "assets": [
            {"id": "edge-cdn", "name": "Cloudflare Edge", "type": "edge", "exposure": "public", "connects_to": ["web-store", "api-gw"]},
            {"id": "web-store", "name": "Storefront Web App", "type": "web_app", "exposure": "public", "connects_to": ["api-gw"]},
            {"id": "api-gw", "name": "Checkout API", "type": "api", "exposure": "public", "connects_to": ["auth-svc", "pg-orders", "s3-assets"]},
            {"id": "admin-portal", "name": "Admin Portal", "type": "admin", "exposure": "public", "connects_to": ["pg-orders", "s3-assets"]},
            {"id": "auth-svc", "name": "Auth Service", "type": "service", "exposure": "internal", "connects_to": ["pg-orders"]},
            {"id": "pg-orders", "name": "Orders DB (Postgres)", "type": "database", "exposure": "internal", "connects_to": [], "crown_jewel": True},
            {"id": "s3-assets", "name": "S3 Bucket: acme-assets", "type": "storage", "exposure": "public", "connects_to": []},
        ],
        "findings": [
            _f("ACME-01", "admin-portal", "Admin portal reachable from the public internet", "high", "exposure",
               ["public_exposure", "admin_panel"],
               "GET https://admin.acme-retail.synthetic/ → 200 OK\nServer: nginx\n<title>Acme Admin · Sign in</title>\nDNS: admin.acme-retail.synthetic → 203.0.113.42 (no IP allow-list)",
               "Administrative interfaces should never be discoverable by anonymous users. Public exposure turns every weak credential into a full compromise.",
               0.97, "Restrict the admin portal to VPN/IP allow-list or place it behind an identity-aware proxy.",
               "P0", "Put the admin portal behind an identity-aware proxy so it is unreachable without corporate SSO.",
               "nginx", "# nginx: restrict admin to corporate ranges\nlocation / {\n    allow 10.20.0.0/16;\n    allow 198.51.100.0/24;\n    deny all;\n    proxy_pass http://admin-portal;\n}"),
            _f("ACME-02", "admin-portal", "Default credentials accepted on admin portal", "critical", "auth",
               ["default_creds", "auth_weakness"],
               "POST /login  user=admin pass=admin123\n→ HTTP 302 Location: /dashboard\nSet-Cookie: session=eyJhbGci... (role=superadmin)",
               "A working default password is the shortest possible path from 'anonymous' to 'superadmin'. No exploit is needed, just a guess.",
               0.99, "Rotate the admin credential immediately and enforce MFA for all admin accounts.",
               "P0", "Rotate the credential now, then require SSO + MFA so passwords alone can never open the portal.",
               "bash", "# Rotate and enforce MFA\nacme-admin users reset-password admin --force-mfa\nacme-admin policy set --require-mfa=true --min-password-length=16"),
            _f("ACME-03", "admin-portal", "No rate limiting on admin login endpoint", "high", "auth",
               ["no_rate_limit", "auth_weakness"],
               "200 POST /login attempts in 12s from one IP\n→ 200 × HTTP 401, no 429, no lockout, no CAPTCHA",
               "Unlimited login attempts let an attacker guess credentials at machine speed, making weak or default passwords trivial to find.",
               0.95, "Add per-IP and per-account rate limiting with progressive lockout.",
               "P1", "Throttle login attempts so credential guessing becomes impractically slow.",
               "nginx", "limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;\nlocation /login {\n    limit_req zone=login burst=5 nodelay;\n    proxy_pass http://admin-portal;\n}"),
            _f("ACME-04", "web-store", "Verbose stack traces expose internal hostnames", "medium", "config",
               ["info_leak"],
               "GET /cart?id=' → HTTP 500\nDjango DEBUG=True\nDATABASE_URL=postgres://orders@pg-orders.internal:5432/orders\nTraceback (most recent call last): ...",
               "Debug output hands attackers a map of your internal network and framework versions, letting them target real weaknesses instead of guessing.",
               0.93, "Disable debug mode in production and return generic error pages.",
               "P2", "Turn off debug output in production so error pages stop leaking internals.",
               "python", "# settings.py\nDEBUG = False\nALLOWED_HOSTS = [\"acme-retail.synthetic\"]\nLOGGING[\"handlers\"][\"console\"][\"level\"] = \"WARNING\""),
            _f("ACME-05", "web-store", "Missing Content-Security-Policy header", "medium", "web",
               ["missing_headers"],
               "GET / → 200 OK\nHeaders present: X-Frame-Options, X-Content-Type-Options\nHeaders missing: Content-Security-Policy",
               "Without CSP, any injected script runs with full trust on the storefront, including in the checkout flow.",
               0.9, "Deploy a Content-Security-Policy that restricts script sources.",
               "P2", "Add a CSP header so injected scripts cannot execute on the storefront.",
               "nginx", "add_header Content-Security-Policy \"default-src 'self'; script-src 'self' https://js.stripe.com; object-src 'none'; frame-ancestors 'none'\" always;"),
            _f("ACME-06", "edge-cdn", "TLS 1.1 still negotiable on origin", "low", "transport",
               ["weak_tls"],
               "openssl s_client -tls1_1 -connect origin.acme-retail.synthetic:443\n→ Protocol: TLSv1.1  Cipher: ECDHE-RSA-AES128-SHA",
               "Legacy TLS versions have known weaknesses that make session interception feasible on hostile networks.",
               0.92, "Disable TLS 1.0/1.1 and restrict cipher suites to modern AEAD ciphers.",
               "P2", "Disable legacy TLS so sessions cannot be downgraded and intercepted.",
               "nginx", "ssl_protocols TLSv1.2 TLSv1.3;\nssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;\nssl_prefer_server_ciphers on;"),
            _f("ACME-07", "api-gw", "Order export endpoint lacks object-level authorization (IDOR)", "high", "web",
               ["idor", "data_access"],
               "GET /api/v1/orders/10422/export  (Authorization: Bearer <user A>)\n→ 200 OK  customer_email=user-b@example.synthetic, last4=4242, address=...",
               "Any logged-in shopper can pull other customers' orders by changing a number in the URL, a direct route to bulk PII theft.",
               0.96, "Enforce ownership checks on every order lookup at the service layer.",
               "P0", "Check that the requesting user owns the order before returning it.",
               "python", "@router.get(\"/orders/{order_id}/export\")\nasync def export_order(order_id: int, user=Depends(current_user)):\n    order = await orders.get(order_id)\n    if order.customer_id != user.id:\n        raise HTTPException(status_code=404)\n    return order.export()"),
            _f("ACME-08", "pg-orders", "Customer PII stored unencrypted at rest", "high", "exposure",
               ["pii_store", "unencrypted"],
               "pg_orders.customers: email, phone, shipping_address, dob (plaintext)\nRDS StorageEncrypted=false · snapshots public=false",
               "If anything upstream is breached, the database gives up every customer record in readable form. Encryption at rest is the last line of defense.",
               0.94, "Enable storage encryption and column-level encryption for sensitive fields.",
               "P1", "Encrypt the database volume and sensitive columns so a breach yields ciphertext, not customer records.",
               "hcl", "resource \"aws_db_instance\" \"orders\" {\n  storage_encrypted = true\n  kms_key_id        = aws_kms_key.orders.arn\n  # ...\n}"),
            _f("ACME-09", "edge-cdn", "Server banner discloses nginx version", "info", "config",
               ["banner"],
               "HTTP/1.1 200 OK\nServer: nginx/1.18.0",
               "Version disclosure narrows an attacker's search for known vulnerabilities. Low impact alone, useful in combination.",
               0.99, "Suppress version tokens in server headers.",
               "P3", "Hide the server version so attackers cannot match it against known CVEs.",
               "nginx", "server_tokens off;"),
            _f("ACME-10", "s3-assets", "Public S3 bucket allows anonymous listing", "medium", "exposure",
               ["public_exposure", "data_access"],
               "GET https://acme-assets.s3.synthetic/ → 200 OK\n<ListBucketResult>\n  <Key>exports/orders-2024-11.csv</Key>\n  <Key>invoices/INV-30112.pdf</Key>",
               "Anyone on the internet can enumerate and download every object, including exports that were never meant to be public.",
               0.98, "Block public access at the account level and serve assets through signed URLs.",
               "P1", "Turn on S3 Block Public Access and move downloads behind signed URLs.",
               "hcl", "resource \"aws_s3_bucket_public_access_block\" \"assets\" {\n  bucket                  = aws_s3_bucket.assets.id\n  block_public_acls       = true\n  block_public_policy     = true\n  ignore_public_acls      = true\n  restrict_public_buckets = true\n}"),
            _f("ACME-11", "web-store", "Session cookie set without Secure flag", "medium", "web",
               ["cookie_insecure"],
               "Set-Cookie: sessionid=9f2c...; Path=/; HttpOnly\n(missing: Secure, SameSite)",
               "A session cookie that can travel over plain HTTP can be captured on a hostile network and replayed to impersonate the shopper.",
               0.91, "Set Secure and SameSite=Lax on all session cookies.",
               "P2", "Mark session cookies Secure so they are never sent over unencrypted connections.",
               "python", "SESSION_COOKIE_SECURE = True\nSESSION_COOKIE_SAMESITE = \"Lax\"\nCSRF_COOKIE_SECURE = True"),
        ],
    },
    {
        "id": "fincorp-bank",
        "name": "FinCorp Bank",
        "tagline": "Core Banking API & Gateway",
        "sector": "Financial services",
        "infra": "Hybrid cloud · Kong Gateway · OAuth2 · Redis · Oracle",
        "description": "Retail banking API gateway handling synthetic account transfers, OAuth2 token issuance and a core ledger.",
        "endpoint_count": 22,
        "assets": [
            {"id": "waf", "name": "Perimeter WAF", "type": "edge", "exposure": "public", "connects_to": ["gateway"]},
            {"id": "gateway", "name": "Kong API Gateway", "type": "api", "exposure": "public", "connects_to": ["oauth-svc", "transfers-api"]},
            {"id": "oauth-svc", "name": "OAuth2 Token Service", "type": "service", "exposure": "public", "connects_to": ["redis-cache", "transfers-api"]},
            {"id": "transfers-api", "name": "Transfers API", "type": "api", "exposure": "internal", "connects_to": ["redis-cache", "core-ledger", "oauth-svc"]},
            {"id": "redis-cache", "name": "Redis Session Cache", "type": "cache", "exposure": "internal", "connects_to": ["transfers-api"]},
            {"id": "core-ledger", "name": "Core Ledger DB", "type": "database", "exposure": "internal", "connects_to": [], "crown_jewel": True},
            {"id": "ops-bastion", "name": "Ops Bastion Host", "type": "host", "exposure": "public", "connects_to": ["core-ledger"]},
        ],
        "findings": [
            _f("FIN-01", "oauth-svc", "JWT validation accepts alg=none", "critical", "auth",
               ["jwt_weak", "auth_weakness"],
               "Token header {\"alg\":\"none\",\"typ\":\"JWT\"} with payload {\"sub\":\"acct-88213\",\"scope\":\"transfers:write\"}\nGET /v2/accounts/me → 200 OK (signature not verified)",
               "Anyone can mint a token claiming to be any customer or operator. This bypasses authentication entirely across every API that trusts the token service.",
               0.99, "Reject unsigned tokens and pin the allowed algorithm list to RS256/ES256.",
               "P0", "Pin accepted JWT algorithms so forged unsigned tokens are rejected.",
               "python", "payload = jwt.decode(\n    token,\n    key=PUBLIC_KEY,\n    algorithms=[\"RS256\"],  # never include 'none'\n    audience=\"fincorp-api\",\n)"),
            _f("FIN-02", "transfers-api", "Server-side request forgery in webhook URL validator", "high", "web",
               ["ssrf"],
               "POST /v2/webhooks {\"url\":\"http://redis-cache.internal:6379/\"}\n→ 200 {\"validated\":true,\"preview\":\"-ERR unknown command 'GET /'\"}",
               "The API will fetch any address on the attacker's behalf, turning a public endpoint into a tunnel into the internal network.",
               0.94, "Resolve and allow-list webhook hosts; block RFC1918 and link-local ranges.",
               "P0", "Only allow webhook URLs that resolve to public, allow-listed hosts.",
               "python", "def validate_webhook(url: str):\n    host = urlparse(url).hostname\n    ip = ipaddress.ip_address(socket.gethostbyname(host))\n    if ip.is_private or ip.is_loopback or ip.is_link_local:\n        raise ValueError(\"internal destinations are not allowed\")"),
            _f("FIN-03", "redis-cache", "Redis session cache reachable without authentication", "high", "exposure",
               ["no_auth_service", "session_store"],
               "redis-cli -h redis-cache.internal PING → PONG\nKEYS sess:* → 41,207 keys\nGET sess:9a1f → {\"sub\":\"acct-10021\",\"role\":\"customer\"}",
               "Every live customer session is readable and writable by anything that can reach this host. Session hijack requires no credentials.",
               0.96, "Enable requirepass/ACLs, bind to private interface, and enable TLS.",
               "P0", "Require authentication and TLS on Redis so sessions cannot be read or forged.",
               "conf", "# redis.conf\nbind 10.40.2.15\nrequirepass ${REDIS_PASSWORD}\ntls-port 6379\nport 0\naclfile /etc/redis/users.acl"),
            _f("FIN-04", "oauth-svc", "OAuth redirect_uri uses wildcard matching", "medium", "auth",
               ["open_redirect", "auth_weakness"],
               "GET /authorize?client_id=mobile&redirect_uri=https://fincorp.synthetic.evil.example/cb\n→ 302 Location: https://fincorp.synthetic.evil.example/cb?code=SplxlOBe...",
               "Authorization codes can be sent to an attacker-controlled site, letting them complete login as the victim.",
               0.9, "Require exact-match redirect URIs registered per client.",
               "P1", "Register exact redirect URIs and reject anything that does not match byte-for-byte.",
               "json", "{\n  \"client_id\": \"mobile\",\n  \"redirect_uris\": [\"https://app.fincorp.synthetic/cb\"],\n  \"redirect_uri_match\": \"exact\"\n}"),
            _f("FIN-05", "transfers-api", "High-value transfers do not require step-up authentication", "high", "auth",
               ["missing_stepup", "data_access"],
               "POST /v2/transfers {\"amount\":250000,\"to\":\"acct-99000\"}\nAuthorization: Bearer <session token>\n→ 201 Created (no MFA challenge, no cooling-off)",
               "A stolen or forged session is enough to move large sums. Step-up auth is what turns a hijacked session into a failed attempt.",
               0.93, "Require MFA re-authentication for transfers above a risk threshold.",
               "P1", "Force an MFA challenge before any transfer above the risk threshold.",
               "python", "if transfer.amount > STEP_UP_THRESHOLD and not session.recent_mfa(minutes=5):\n    raise StepUpRequired(challenge=\"totp\")"),
            _f("FIN-06", "gateway", "HSTS header not set", "medium", "transport",
               ["missing_hsts"],
               "GET https://api.fincorp.synthetic/ → 200 OK\n(missing: Strict-Transport-Security)",
               "Without HSTS, a user's first request can be downgraded to HTTP and intercepted on a hostile network.",
               0.95, "Set Strict-Transport-Security with preload.",
               "P2", "Add HSTS so browsers refuse to talk to the API over plain HTTP.",
               "yaml", "plugins:\n  - name: response-transformer\n    config:\n      add:\n        headers:\n          - \"Strict-Transport-Security: max-age=63072000; includeSubDomains; preload\""),
            _f("FIN-07", "gateway", "CORS reflects arbitrary origin with credentials", "low", "web",
               ["cors_misconfig"],
               "Origin: https://evil.example\n→ Access-Control-Allow-Origin: https://evil.example\n   Access-Control-Allow-Credentials: true",
               "Any website a customer visits can silently call the banking API with their cookies and read the response.",
               0.92, "Allow-list trusted origins and never reflect the request origin.",
               "P2", "Restrict CORS to the bank's own web origins.",
               "yaml", "plugins:\n  - name: cors\n    config:\n      origins:\n        - https://app.fincorp.synthetic\n      credentials: true"),
            _f("FIN-08", "gateway", "GraphQL introspection enabled in production", "info", "config",
               ["info_leak"],
               "POST /graphql {\"query\":\"{ __schema { types { name fields { name } } } }\"}\n→ 200 OK  types: Account, Transfer, WebhookConfig(url, secret), InternalAuditLog",
               "Introspection publishes the full API surface, including internal types that hint at where sensitive functionality lives.",
               0.97, "Disable introspection outside development.",
               "P3", "Turn off schema introspection in production.",
               "javascript", "const server = new ApolloServer({\n  schema,\n  introspection: process.env.NODE_ENV !== \"production\",\n});"),
            _f("FIN-09", "core-ledger", "Ledger replication user holds superuser privileges", "high", "exposure",
               ["pii_store", "excessive_privilege"],
               "SELECT rolname, rolsuper FROM pg_roles WHERE rolname='repl_svc' → t\nTables: accounts(ssn, dob), transactions, kyc_documents",
               "A replication account should only read WAL. With superuser it can read, alter or delete every account record and audit log.",
               0.95, "Grant REPLICATION only; revoke SUPERUSER from service roles.",
               "P1", "Reduce the replication account to the minimum privilege it actually needs.",
               "sql", "ALTER ROLE repl_svc NOSUPERUSER;\nALTER ROLE repl_svc REPLICATION;\nREVOKE ALL ON SCHEMA public FROM repl_svc;"),
            _f("FIN-10", "ops-bastion", "Bastion host allows SSH password authentication", "medium", "config",
               ["weak_ssh", "public_exposure"],
               "ssh -o PreferredAuthentications=password ops@bastion.fincorp.synthetic\n→ ops@bastion's password:  (PasswordAuthentication yes, no MFA)",
               "A password-only bastion facing the internet is a brute-force target with a direct line to the ledger database.",
               0.93, "Disable password auth; require certificates or hardware keys plus MFA.",
               "P1", "Switch the bastion to key-based SSH with MFA and disable passwords.",
               "conf", "# /etc/ssh/sshd_config\nPasswordAuthentication no\nPubkeyAuthentication yes\nAuthenticationMethods publickey,keyboard-interactive"),
        ],
    },
    {
        "id": "healthops",
        "name": "HealthOps",
        "tagline": "Patient Portal & FHIR API",
        "sector": "Healthcare",
        "infra": "Azure · Kubernetes · FHIR API · Blob Storage",
        "description": "Patient-facing EHR portal managing synthetic medical records, provider identities and clinical backups.",
        "endpoint_count": 18,
        "assets": [
            {"id": "portal", "name": "Patient Portal", "type": "web_app", "exposure": "public", "connects_to": ["fhir-api", "idp"]},
            {"id": "fhir-api", "name": "FHIR API", "type": "api", "exposure": "public", "connects_to": ["ehr-db", "telemetry"]},
            {"id": "idp", "name": "Provider Identity (IdP)", "type": "service", "exposure": "public", "connects_to": ["fhir-api"]},
            {"id": "k8s-cluster", "name": "Kubernetes Dashboard", "type": "admin", "exposure": "public", "connects_to": ["ehr-db", "fhir-api", "backup-blob"]},
            {"id": "ehr-db", "name": "EHR Database", "type": "database", "exposure": "internal", "connects_to": [], "crown_jewel": True},
            {"id": "backup-blob", "name": "Blob: clinical-backups", "type": "storage", "exposure": "public", "connects_to": []},
            {"id": "telemetry", "name": "Telemetry Collector", "type": "service", "exposure": "internal", "connects_to": []},
        ],
        "findings": [
            _f("HO-01", "fhir-api", "FHIR API returns records for any patient ID (BOLA)", "critical", "web",
               ["idor", "data_access"],
               "GET /fhir/Patient/8821  (Bearer token for patient 1044)\n→ 200 OK {\"resourceType\":\"Patient\",\"name\":\"<redacted>\",\"birthDate\":\"1971-03-08\", ...}",
               "Every patient in the system can read every other patient's chart. This is a reportable breach the moment anyone notices.",
               0.98, "Enforce patient-scoped authorization on every FHIR resource read.",
               "P0", "Scope each request to the patient (or provider relationship) the token actually belongs to.",
               "python", "@router.get(\"/fhir/Patient/{pid}\")\nasync def get_patient(pid: str, ctx=Depends(auth_context)):\n    if not ctx.can_access_patient(pid):\n        raise HTTPException(403)\n    return await fhir.patient(pid)"),
            _f("HO-02", "k8s-cluster", "Kubernetes dashboard exposed with cluster-admin service account", "high", "exposure",
               ["public_exposure", "admin_panel", "default_creds"],
               "GET https://k8s.healthops.synthetic/#/workloads → 200 OK (skip-login enabled)\nServiceAccount kubernetes-dashboard bound to ClusterRole cluster-admin",
               "Anyone who finds this URL can run commands in the cluster that hosts the EHR database. No password, no exploit.",
               0.97, "Remove public ingress, disable skip-login and bind a least-privilege role.",
               "P0", "Take the dashboard off the internet and strip its cluster-admin binding.",
               "yaml", "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: dashboard-viewer\n  namespace: kubernetes-dashboard\nroleRef:\n  kind: ClusterRole\n  name: view\nsubjects:\n  - kind: ServiceAccount\n    name: kubernetes-dashboard"),
            _f("HO-03", "backup-blob", "Clinical backup container is publicly listable", "high", "exposure",
               ["public_exposure", "data_access"],
               "GET https://healthopsbk.blob.synthetic/clinical-backups?restype=container&comp=list\n→ 200 OK  <Blob><Name>ehr-full-2024-11-30.bak</Name><Properties><Content-Length>48213377024</Content-Length>",
               "Full database backups are downloadable by anyone. This is the entire patient record set in one file.",
               0.98, "Set container access to private and rotate the storage keys.",
               "P0", "Make the backup container private and rotate its access keys.",
               "bash", "az storage container set-permission \\\n  --name clinical-backups --public-access off\naz storage account keys renew --account-name healthopsbk --key primary"),
            _f("HO-04", "ehr-db", "EHR database stores PHI without encryption at rest", "critical", "exposure",
               ["pii_store", "unencrypted"],
               "Azure SQL TDE: Disabled\nColumns: patients.ssn, encounters.diagnosis_codes, notes.body (plaintext)",
               "Protected health information in plaintext means any successful intrusion becomes a full HIPAA breach with mandatory notification.",
               0.96, "Enable Transparent Data Encryption and field-level encryption for identifiers.",
               "P1", "Encrypt the database so stolen storage yields nothing readable.",
               "bash", "az sql db tde set --status Enabled \\\n  --database ehr --server healthops-sql --resource-group healthops-prod"),
            _f("HO-05", "portal", "Session cookies missing Secure and HttpOnly flags", "medium", "web",
               ["cookie_insecure"],
               "Set-Cookie: portal_session=c81e...; Path=/\n(missing: Secure, HttpOnly, SameSite)",
               "Patient sessions can be read by injected scripts or captured on hostile networks, then replayed.",
               0.94, "Set Secure, HttpOnly and SameSite on session cookies.",
               "P2", "Harden the session cookie so it cannot be stolen by scripts or sniffed in transit.",
               "javascript", "app.use(session({\n  cookie: { secure: true, httpOnly: true, sameSite: \"lax\" },\n}));"),
            _f("HO-06", "portal", "Weak TLS cipher suites and TLS 1.0 enabled", "medium", "transport",
               ["weak_tls"],
               "testssl portal.healthops.synthetic\n→ TLS 1.0 offered · RC4-SHA accepted · SWEET32 vulnerable",
               "Legacy ciphers let a network attacker decrypt or tamper with patient traffic, including session cookies.",
               0.93, "Restrict to TLS 1.2+ with AEAD ciphers only.",
               "P2", "Remove legacy TLS and ciphers so patient traffic cannot be decrypted in transit.",
               "yaml", "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  annotations:\n    nginx.ingress.kubernetes.io/ssl-protocols: \"TLSv1.2 TLSv1.3\"\n    nginx.ingress.kubernetes.io/ssl-ciphers: \"ECDHE-ECDSA-AES256-GCM-SHA384\""),
            _f("HO-07", "idp", "MFA not enforced for provider accounts", "medium", "auth",
               ["auth_weakness", "no_mfa"],
               "Conditional Access policies: 0 enforcing MFA\n1,204 provider accounts · 312 with MFA registered · 892 password-only",
               "Clinician accounts see thousands of charts. A single phished password becomes wholesale record access.",
               0.95, "Enforce MFA for all provider and admin roles via conditional access.",
               "P1", "Require MFA for every clinician and admin login.",
               "json", "{\n  \"displayName\": \"Require MFA - providers\",\n  \"state\": \"enabled\",\n  \"conditions\": {\"users\": {\"includeGroups\": [\"providers\"]}},\n  \"grantControls\": {\"builtInControls\": [\"mfa\"]}\n}"),
            _f("HO-08", "idp", "Password reset tokens valid for 24 hours", "low", "auth",
               ["weak_token"],
               "GET /reset?token=... (issued 23h ago) → 200 OK form rendered",
               "Long-lived reset links widen the window in which a leaked email or log entry lets someone take over an account.",
               0.9, "Reduce token lifetime to 15 minutes and single use.",
               "P3", "Shorten reset links to 15 minutes and burn them after one use.",
               "python", "RESET_TOKEN_TTL_SECONDS = 900\nRESET_TOKEN_SINGLE_USE = True"),
            _f("HO-09", "portal", "X-Powered-By header exposes framework", "info", "config",
               ["banner"],
               "HTTP/1.1 200 OK\nX-Powered-By: Express",
               "Framework disclosure is minor on its own but helps attackers pick tooling.",
               0.99, "Remove X-Powered-By.",
               "P3", "Drop the framework banner header.",
               "javascript", "app.disable(\"x-powered-by\");"),
            _f("HO-10", "telemetry", "Telemetry collector logs full request bodies including PHI", "medium", "config",
               ["info_leak", "pii_store"],
               "otel-collector logs: {\"path\":\"/fhir/Patient\",\"body\":{\"name\":\"<redacted>\",\"ssn\":\"***-**-4410\",...}}\nRetention: 400 days · Access: all engineers",
               "PHI is duplicated into a low-security log system with broad access, multiplying the number of places it can leak from.",
               0.92, "Redact request bodies at the collector and restrict log access.",
               "P2", "Redact sensitive fields before they hit logs and lock down who can read them.",
               "yaml", "processors:\n  attributes/redact:\n    actions:\n      - key: http.request.body\n        action: delete\n      - key: patient.ssn\n        action: hash"),
        ],
    },
]


def get_environment(env_id: str):
    return next((e for e in ENVIRONMENTS if e["id"] == env_id), None)
