"""Preloaded demo incident: 'Suspicious admin login' on Acme Retail. Static replay; AI text is pre-generated and labeled."""

DEMO_INCIDENT = {
    "id": "INC-DEMO-001",
    "title": "Suspicious admin login",
    "environment_id": "acme-retail",
    "synthetic": True,
    "summary": "An admin-portal session was established from an unfamiliar network after a burst of failed logins.",
    "steps": [
        {
            "key": "detect",
            "index": 1,
            "name": "Detect",
            "headline": "Anomalous admin session from unfamiliar ASN",
            "description": "Login telemetry on the Admin Portal shows 47 failed attempts in 11 seconds from 185.220.101.7 (AS205100, not seen before), followed by a successful login for account 'admin' at 03:12:44 UTC.",
            "evidence": [
                "03:12:33Z  POST /login user=admin  → 401  (x47, 11s window, src=185.220.101.7)",
                "03:12:44Z  POST /login user=admin  → 302 /dashboard  Set-Cookie: session=…role=superadmin",
                "GeoIP: src ASN AS205100 · first-seen for tenant acme-retail · impossible-travel vs last admin login (Seattle, 2h earlier)",
            ],
            "finding_ids": ["ACME-03"],
            "duration_ms": 1800,
        },
        {
            "key": "investigate",
            "index": 2,
            "name": "Investigate",
            "headline": "Login succeeded with a default credential on an internet-facing portal",
            "description": "The successful attempt used the vendor default 'admin / admin123'. The portal has no IP allow-list and no lockout, so the burst was a straightforward online guess, not a token theft.",
            "evidence": [
                "Credential match: default vendor pair admin/admin123 (finding ACME-02)",
                "Portal ingress: 0.0.0.0/0 allowed, no IAP, no VPN requirement (finding ACME-01)",
                "No 429 responses in window · lockout policy: none (finding ACME-03)",
            ],
            "finding_ids": ["ACME-01", "ACME-02", "ACME-03"],
            "duration_ms": 1800,
        },
        {
            "key": "correlate",
            "index": 3,
            "name": "Correlate",
            "headline": "Foothold has a direct route to the Orders DB and public bucket",
            "description": "Deterministic rules R01, R02 and R06 link the exposed portal, the missing throttle and the default credential into a validated chain that terminates at the unencrypted Orders database. A second branch reaches the publicly listable S3 bucket.",
            "evidence": [
                "R01 public_exposure → default_creds (same asset admin-portal)",
                "R02 no_rate_limit → default_creds (same asset admin-portal)",
                "R06 default_creds → pii_store (admin-portal → pg-orders)",
                "R05 default_creds → data_access (admin-portal → s3-assets)",
            ],
            "finding_ids": ["ACME-01", "ACME-02", "ACME-03", "ACME-08", "ACME-10"],
            "path_node_ids": ["ACME-01", "ACME-02", "ACME-08"],
            "duration_ms": 2200,
        },
        {
            "key": "explain",
            "index": 4,
            "name": "Explain",
            "headline": "What this means for the business",
            "description": "AI interpretation over the validated chain only.",
            "observed_evidence": [
                "Successful superadmin session from a first-seen network using a default credential.",
                "Admin portal is internet-reachable with no throttling or lockout.",
                "Admin portal has a network route to the Orders DB, which stores customer PII in plaintext.",
            ],
            "ai_interpretation": "An outside party now holds the highest-privilege session in the retail stack, obtained by guessing rather than hacking. From this seat the likely objective is bulk export of customer orders, which would expose names, addresses and partial card data for every shopper and trigger PCI-DSS and GDPR notification duties. Because the database is unencrypted, there is no secondary barrier once the admin session is used. Treat this as an active breach-in-progress with a customer-data blast radius, not as a suspicious login.",
            "confidence": 0.91,
            "finding_ids": ["ACME-02", "ACME-08"],
            "duration_ms": 2200,
        },
        {
            "key": "recommend",
            "index": 5,
            "name": "Recommend",
            "headline": "Contain now, harden next",
            "description": "Ordered by risk reduction per minute of effort.",
            "actions": [
                {"priority": "P0", "title": "Kill the active session and rotate the admin credential", "detail": "Invalidate all admin-portal sessions, reset 'admin', enforce MFA.", "finding_id": "ACME-02", "snippet_language": "bash", "snippet": "acme-admin sessions revoke --all --role=superadmin\nacme-admin users reset-password admin --force-mfa"},
                {"priority": "P0", "title": "Pull the admin portal off the public internet", "detail": "Restrict ingress to corporate ranges or an identity-aware proxy.", "finding_id": "ACME-01", "snippet_language": "nginx", "snippet": "allow 10.20.0.0/16;\ndeny all;"},
                {"priority": "P1", "title": "Throttle login attempts", "detail": "Per-IP and per-account limits with progressive lockout.", "finding_id": "ACME-03", "snippet_language": "nginx", "snippet": "limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;"},
                {"priority": "P1", "title": "Encrypt the Orders DB", "detail": "Enable storage encryption so a repeat intrusion yields ciphertext.", "finding_id": "ACME-08", "snippet_language": "hcl", "snippet": "storage_encrypted = true"},
            ],
            "finding_ids": ["ACME-01", "ACME-02", "ACME-03", "ACME-08"],
            "duration_ms": 1500,
        },
    ],
}
